# Generated by Django 3.1.7 on 2021-03-19 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('opis', models.TextField(max_length=500)),
                ('czy_dostepny', models.BooleanField(default=True)),
                ('cena', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)])),
            ],
            options={
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Sklep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_sklepu', models.CharField(max_length=30)),
                ('adres_sklepu', models.URLField()),
                ('nip', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('produkty', models.ManyToManyField(to='api.Produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentarz', models.TextField(default='', max_length=500)),
                ('gwiazdki', models.IntegerField(choices=[(4, '4/5 Dobry produkt'), (1, '1/5 Zbyt Kiepski produkt'), (2, '2/5 Slaby produkt'), (5, '5/5 Bardzo Dobry Produkt'), (3, '3/5 Średni produkt')], default=5)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(default='', max_length=30)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinie', to='api.produkt')),
            ],
            options={
                'ordering': ['data_dodania'],
            },
        ),
    ]
