# Generated by Django 3.1.7 on 2021-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinia',
            name='autor',
            field=models.CharField(default='', max_length=30),
        ),
    ]
