# Generated by Django 3.1.7 on 2021-03-22 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210322_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinia',
            name='gwiazdki',
            field=models.IntegerField(choices=[(5, '5/5 Bardzo Dobry Produkt'), (4, '4/5 Dobry produkt'), (2, '2/5 Slaby produkt'), (1, '1/5 Zbyt Kiepski produkt'), (3, '3/5 Średni produkt')], default=5),
        ),
        migrations.AlterField(
            model_name='sklep',
            name='adres_sklepu',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sklep',
            name='nip',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
