# Generated by Django 3.1.7 on 2021-03-22 18:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210322_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinia',
            name='gwiazdki',
            field=models.IntegerField(choices=[(1, '1/5 Zbyt Kiepski produkt'), (4, '4/5 Dobry produkt'), (2, '2/5 Slaby produkt'), (3, '3/5 Średni produkt'), (5, '5/5 Bardzo Dobry Produkt')], default=5),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='nazwa',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sklep',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='sklep',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
