# Generated by Django 3.1.7 on 2021-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210322_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_testowa', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='opinia',
            name='gwiazdki',
            field=models.IntegerField(choices=[(4, '4/5 Dobry produkt'), (5, '5/5 Bardzo Dobry Produkt'), (1, '1/5 Zbyt Kiepski produkt'), (2, '2/5 Slaby produkt'), (3, '3/5 Średni produkt')], default=5),
        ),
    ]
