# Generated by Django 3.1.7 on 2021-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210322_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='testowa',
            name='adres_sklepu',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opinia',
            name='gwiazdki',
            field=models.IntegerField(choices=[(1, '1/5 Zbyt Kiepski produkt'), (2, '2/5 Slaby produkt'), (3, '3/5 Średni produkt'), (5, '5/5 Bardzo Dobry Produkt'), (4, '4/5 Dobry produkt')], default=5),
        ),
    ]
