# Generated by Django 3.1.7 on 2021-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210322_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinia',
            name='gwiazdki',
            field=models.IntegerField(choices=[(2, '2/5 Slaby produkt'), (3, '3/5 Średni produkt'), (1, '1/5 Zbyt Kiepski produkt'), (4, '4/5 Dobry produkt'), (5, '5/5 Bardzo Dobry Produkt')], default=5),
        ),
    ]
