# Generated by Django 3.1.7 on 2021-03-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210322_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklep',
            name='produkty',
            field=models.ManyToManyField(blank=True, related_name='produkty', to='api.Produkt'),
        ),
        migrations.AlterField(
            model_name='opinia',
            name='gwiazdki',
            field=models.IntegerField(choices=[(2, '2/5 Slaby produkt'), (5, '5/5 Bardzo Dobry Produkt'), (3, '3/5 Średni produkt'), (4, '4/5 Dobry produkt'), (1, '1/5 Zbyt Kiepski produkt')], default=5),
        ),
        migrations.DeleteModel(
            name='Testowa',
        ),
    ]
